ng14
angular-buch/website-articles pull request #17
Opened 2022-05-21 09:00 UTC by fmalcher

2022-05-21 10:13 UTC, JohannesHoppe commented on blog/2022-06-angular14/README.md
> +Während die letzten Hauptreleases vor allem interne Verbesserungen für das Tooling mitbrachten, hat Angular 14 einige spannende neue FEatures mit an Bord.
```suggestion
Während die letzten Hauptreleases vor allem interne Verbesserungen für das Tooling mitbrachten, hat Angular 14 einige spannende neue Features mit an Board.
```

2022-05-21 10:27 UTC, fmalcher commented on blog/2022-06-angular14/README.md
> +Während die letzten Hauptreleases vor allem interne Verbesserungen für das Tooling mitbrachten, hat Angular 14 einige spannende neue FEatures mit an Bord.
"an Bord" ist korrekt 😉

2022-05-28 08:16 UTC, d-koppenhagen requested changes

2022-05-28 08:16 UTC, d-koppenhagen commented on blog/2022-06-angular14/README.md
> +Noch bevor die Sommer- und Urlaubszeit beginnt, wartet Angular mit tollen Neuigkeiten auf: Am TODO. Juni 2022 erschien die neue Major-Version **Angular 14**!
Nur ein Kommentar, damit wir nicht aus Versehen das Todo stehen lassen vor dem Publish

2022-05-28 08:17 UTC, d-koppenhagen requested changes

2022-05-28 08:17 UTC, d-koppenhagen commented on blog/2022-06-angular14/README.md
> +Im englischsprachigen [Angular-Blog](TODO) finden Sie außerdem die offizielle Mitteilung des Angular-Teams.
Same here: Link ergänzen

2022-05-28 09:09 UTC, JohannesHoppe approved these changes

2022-05-28 09:09 UTC, JohannesHoppe commented on blog/2022-06-angular14/README.md
> +Prüfen Sie danach am Besten mithilfe von Git die Änderungen.
```suggestion
Prüfen Sie danach am Besten mithilfe der Differenzansicht von Git die Änderungen.
```

2022-05-28 09:09 UTC, JohannesHoppe commented on blog/2022-06-angular14/README.md
> +Insbesondere bei Wiederverwandbaren Komponenten führte das schnell zu Chaos.
```suggestion
Insbesondere bei wiederverwendbaren Komponenten führte das leicht zu unübersichtlichen Code.
```

2022-05-28 09:09 UTC, JohannesHoppe commented on blog/2022-06-angular14/README.md
> +Damit eine Komponente genutzt werden kann, muss sie direkt am Ort der VErwendung importiert werden.
```suggestion
Damit eine Komponente genutzt werden kann, muss sie direkt am Ort der Verwendung importiert werden.
```

2022-05-28 09:09 UTC, JohannesHoppe commented on blog/2022-06-angular14/README.md
> +Die Angular CLI bietet ein praktisches neues Feature an: eine integrierte Auto Completion für die Shell.
```suggestion
Die Angular CLI bietet ein praktisches neues Feature an: eine integrierte automatische Vervollständigung für die Kommandozeile.
```

2022-05-28 09:27 UTC, JohannesHoppe commented
Inhaltlich habe ich keine Einwände. Sieht alles sehr gut aus. 👍

2022-06-02 19:09 UTC, merged